version: "3"
services:
  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
